import 'dart:math';

class DataStorage {
  static final Random _random = Random();

  static const List<String> names = [
    "Akari",
    "Hikari",
    "Yuki",
    "Sakura",
    "Mizuki",
    "Aoi",
    "Rika",
    "Kaori",
    "Nanami",
    "Haruka",
    "Reina",
    "Tsukiko",
    "Emiko",
    "Natsumi",
    "Kohana",
    "Midori",
    "Chiyo",
    "Sumire",
    "Hinata",
    "Ayame",
    "Rin",
    "Saya",
    "Yumeko",
    "Misaki",
    "Eri",
    "Hotaru",
    "Meiko",
    "Fuyuko",
    "Noriko",
    "Asami",
    "Tomoe",
    "Momoka",
    "Kazumi",
    "Saeko",
    "Hitomi",
    "Mayumi",
    "Shizuku",
    "Tamiko",
    "Nozomi",
    "Kotone",
    "Riko",
    "Miki",
    "Satomi",
    "Kairi",
    "Mai",
    "Takara",
    "Minami",
    "Tsubaki",
    "Satsuki",
    "Yuna",
    "Naoko",
    "Akemi"
  ];

  static const List<String> origins = [
    "Moonlit Kingdom",
    "Celestial Realm",
    "Mystic Forest",
    "Ethereal Highlands",
    "Shadowed Vale",
    "Dragon’s Nest",
    "Enchanted Isles",
    "Nebula Sanctuary",
    "Forgotten Shrine",
    "Crimson Empire",
    "Starfall Haven",
    "Shimmering Glades",
    "Frozen Tundra",
    "Silverwood Grove",
    "Twilight Caverns",
    "Sunken Ruins",
    "Abyssal Depths",
    "Thunderclap Peaks",
    "Velvet Horizon",
    "Lunar Academy",
    "Crystal Palace",
    "Emerald Abyss",
    "Celestial Garden",
    "Echoing Halls",
    "Hidden Monastery",
    "Stormborn Keep",
    "Ancient Library",
    "Golden Plains",
    "Silent Observatory",
    "Radiant Expanse",
    "Violet Reaches",
    "Serpent's Cove",
    "Astral Wastes",
    "Skyward Keep",
    "Obsidian Tower",
    "Serene Waters",
    "Eldritch Dominion",
    "Hallowed Grounds",
    "Arcane Spire",
    "Whispering Meadows",
    "Evergloom Thicket",
    "Mistral Bastion",
    "Phoenix Sanctuary",
    "Midnight Fjord",
    "Harmonic Reef",
    "Infinite Horizon",
    "Suncrest Haven",
    "Oracle's Refuge",
    "Boreal Citadel",
    "Frostveil Sanctuary"
  ];

  static const List<String> descriptions = [
    "A mischievous catgirl with a love for adventure.",
    "A gentle spirit who adores moonlit strolls.",
    "A playful trickster who always has a riddle to share.",
    "A devoted guardian from an ancient bloodline.",
    "A starry-eyed dreamer seeking the ultimate magic.",
    "A skilled alchemist, always tinkering with new potions.",
    "A shy poet who writes verses under cherry blossoms.",
    "A legendary swordswoman with a mysterious past.",
    "A master of illusion, weaving dreams into reality.",
    "A curious explorer who maps the unknown lands.",
    "A sorceress blessed with celestial powers.",
    "A herbalist who can talk to plants and animals.",
    "A cunning strategist, feared on the battlefield.",
    "A painter who captures the essence of spirits.",
    "A shape-shifter with a mischievous streak.",
    "A priestess dedicated to preserving harmony.",
    "A healer who soothes wounds with a single touch.",
    "A songstress whose voice enchants all who listen.",
    "A mysterious wanderer who never stays in one place.",
    "A warrior trained by the ancient feline masters.",
    "A scholar seeking the secrets of the universe.",
    "A playful dancer who can summon glowing lights.",
    "A chef who creates magical feasts with a flick of her wrist.",
    "A librarian who guards forbidden tomes.",
    "A guardian of an ancient celestial relic.",
    "A noblewoman with a tragic secret.",
    "A swift messenger with boundless energy.",
    "A caretaker of abandoned kittens and lost souls.",
    "A playful spirit with an affinity for storms.",
    "A fearless bounty hunter who never backs down.",
    "A soft-spoken artisan who weaves enchanted fabrics.",
    "A forgotten deity reincarnated into a catgirl.",
    "A loyal knight sworn to an ancient order.",
    "A traveling fortune teller with cryptic messages.",
    "A rogue with a heart of gold.",
    "A dancer who moves with the grace of flowing water.",
    "A researcher obsessed with unraveling forgotten lore.",
    "A thief who steals not for wealth, but for justice.",
    "A celestial emissary with a mission from the stars.",
    "A guardian of an enchanted spring with healing waters.",
    "A joyful prankster who spreads laughter wherever she goes.",
    "A guide who helps lost souls find their way.",
    "A protector of sacred ruins hidden deep in the forest.",
    "A warrior of light, always fighting for justice.",
    "A storyteller whose words can reshape reality.",
    "A lone wanderer searching for her true home.",
    "A descendant of an ancient feline queen.",
    "A seeker of forbidden knowledge.",
    "A knight from a fallen kingdom, searching for redemption.",
    "A mystic who can commune with spirits."
  ];

  static const List<String> titles = [
    "Adventurous Wanderer",
    "Moonlit Dreamer",
    "Clever Trickster",
    "Ancient Guardian",
    "Magic Seeker",
    "Potion Master",
    "Cherry Blossom Poet",
    "Legendary Blade",
    "Illusion Weaver",
    "Curious Explorer",
    "Celestial Sorceress",
    "Nature Whisperer",
    "Battlefield Strategist",
    "Spirit Painter",
    "Mischief Shapeshifter",
    "Harmony Keeper",
    "Healing Touch",
    "Enchanting Songstress",
    "Mystic Wanderer",
    "Feline Warrior",
    "Universe Scholar",
    "Light Dancer",
    "Magical Chef",
    "Forbidden Librarian",
    "Celestial Guardian",
    "Tragic Noble",
    "Swift Messenger",
    "Kitten Caretaker",
    "Storm Spirit",
    "Fearless Hunter",
    "Artisan Weaver",
    "Reincarnated Deity",
    "Loyal Knight",
    "Cryptic Fortune Teller",
    "Golden-Hearted Rogue",
    "Water Grace Dancer",
    "Lost Lore Researcher",
    "Justice Thief",
    "Astral Emissary",
    "Enchanted Spring Keeper",
    "Laughing Prankster",
    "Soul Guide",
    "Sacred Ruins Protector",
    "Light Warrior",
    "Reality Storyteller",
    "Wandering Seeker",
    "Feline Queen Descendant",
    "Forbidden Knowledge Seeker",
    "Fallen Kingdom Knight",
    "Spirit Mystic"
  ];

  static String getRandomName() => names[_random.nextInt(names.length)];
  static String getRandomOrigin() => origins[_random.nextInt(origins.length)];
  static String getRandomDescription() =>
      descriptions[_random.nextInt(descriptions.length)];
  static String getRandomTitle() => titles[_random.nextInt(titles.length)];
}
